version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=apigolangpersons      
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/personalities.sql:/docker-entrypoint-initdb.d/personalities.sql   